#!/usr/bin/env python3
"""Generate V2__seed_reference.sql from the real Wardah SKU list.

Source: ../Grab Kilat Fulfillment/wardah_sku_list.csv (108 recovered SKUs of 118).

Seeds enough to run and test the whole app before a rack exists:
  - Wardah brand + the 108 SKUs with real names, categories, prices, unit cubes
  - a deterministic synthetic EAN-13 per SKU, clearly marked as test data, so
    scanning can be exercised without physical stock (PRD M8.4.4)
  - a "Kirana Beauty" second brand in Mode B, to exercise license plates
  - the real station list from HANDOFF §14, plus MAC-TRN, the training site
  - a full 7-rack / 5-level / 3-position layout for the training site

Re-run after changing the CSV:  python tools/gen_seed_migration.py
"""
import csv
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
CSV_PATH = ROOT.parent / "Grab Kilat Fulfillment" / "wardah_sku_list.csv"
OUT = ROOT / "backend" / "resources" / "db" / "migration" / "V2__seed_reference.sql"


def esc(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("\\", "\\\\").replace("'", "''") + "'"


def num(v):
    if v is None or str(v).strip() == "":
        return "NULL"
    d = re.sub(r"[^0-9]", "", str(v))
    return d if d else "NULL"


def ean13(seed: int) -> str:
    """Deterministic, checksum-valid EAN-13 in the 299 'internal use' prefix.

    299 is reserved for in-store/internal numbering, so these can never collide
    with a real manufacturer GTIN. They exist so the scan path is testable.
    """
    body = f"299{seed:09d}"
    total = sum(int(d) * (3 if i % 2 else 1) for i, d in enumerate(body))
    return body + str((10 - total % 10) % 10)


def expiry_tier(name: str, category: str) -> str:
    n = name.lower()
    if "uv shield" in n or "uv acne" in n or "c-defense" in n or "c defense" in n:
        return "critical"
    if category in ("Face Care", "Sun Care"):
        return "watch"
    return "stable"


def main():
    rows = []
    with CSV_PATH.open(encoding="utf-8-sig", newline="") as fh:
        for r in csv.DictReader(fh):
            name = (r.get("Product name (as shown in app)") or "").strip()
            # the CSV is an OCR artefact and carries a trailing formula row
            if not name or name.startswith("="):
                continue
            idx = (r.get("#") or "").strip()
            if not idx.isdigit():
                continue
            rows.append(
                {
                    "n": int(idx),
                    "category": (r.get("Category") or "").strip(),
                    "line": (r.get("Product line") or "").strip(),
                    "name": name,
                    "size": (r.get("Unit size") or "").strip(),
                    "price": num(r.get("Price (Rp)")),
                    "cube": num(r.get("Est. unit cube incl. carton (cm3)")),
                }
            )

    out = []
    w = out.append
    w("-- GENERATED by tools/gen_seed_migration.py — do not edit by hand.")
    w("-- Reference + test data. Real SKU names; synthetic EAN-13s (prefix 299,")
    w("-- the internal-use range) so scanning is testable without physical stock.")
    w("")
    w("INSERT INTO brands (id, code, name, identity_mode) VALUES")
    w("  (1, 'WRD', 'Wardah Official Store', 'sku_barcode'),")
    w("  (2, 'KRN', 'Kirana Beauty (unbarcoded, Mode B)', 'unit_label');")
    w("")
    w("-- Stations from HANDOFF §14. Addresses are authoritative; names lie.")
    w("INSERT INTO sites (id, code, name, address, site_type, is_training) VALUES")
    w("  (1, 'MAC-MAC', 'Logos Metrolink Hub', 'Medan Satria, Bekasi', 'hub', 0),")
    w("  (2, 'MAC-KJR', 'Kemanggisan', 'Kec. Palmerah, Jakarta Barat', 'darkstore', 0),")
    w("  (3, 'MAC-UT5', 'Johar Baru', 'Johar Baru, Jakarta Pusat', 'darkstore', 0),")
    w("  (4, 'MAC-MA5', 'Kalibata', 'Jl. Raya Kalibata No. 4, Kramat Jati', 'darkstore', 0),")
    w("  (5, 'MAC-KD5', 'Krukut', 'Kec. Limo, Kota Depok', 'darkstore', 0),")
    w("  (6, 'KOI-CP5', 'Cempaka Putih', NULL, 'darkstore', 0),")
    w("  (7, 'MAC-CB5', 'Cibinong', 'Cibinong, Bogor', 'darkstore', 0),")
    w("  (8, 'MAC-RBU', 'New Rawa Lumbu', 'Rawa Lumbu, Bekasi', 'darkstore', 0),")
    w("  (99, 'MAC-TRN', 'Latihan / Training', 'Training site — not a real location', 'darkstore', 1);")
    w("")
    w("INSERT INTO brand_sites (brand_id, site_id, active)")
    w("  SELECT b.id, s.id, 1 FROM brands b CROSS JOIN sites s;")
    w("")

    w("-- 108 recovered Wardah SKUs (of 118). Source: wardah_sku_list.csv.")
    w("INSERT INTO skus (id, brand_id, brand_sku_code, name_display, category,")
    w("                  product_line, unit_size, price_idr, unit_cube_cm3,")
    w("                  expiry_tier, identity_mode) VALUES")
    vals = []
    for r in rows:
        sku_id = r["n"]
        vals.append(
            "  ({id}, 1, {code}, {name}, {cat}, {line}, {size}, {price}, {cube}, {tier}, 'sku_barcode')".format(
                id=sku_id,
                code=esc(f"WRD-{r['n']:04d}"),
                name=esc(r["name"]),
                cat=esc(r["category"]),
                line=esc(r["line"]),
                size=esc(r["size"]),
                price=r["price"],
                cube=r["cube"],
                tier=esc(expiry_tier(r["name"], r["category"])),
            )
        )
    w(",\n".join(vals) + ";")
    w("")

    w("-- A small Mode B brand so license plates can be exercised end to end.")
    w("INSERT INTO skus (id, brand_id, brand_sku_code, name_display, category,")
    w("                  product_line, unit_size, price_idr, unit_cube_cm3,")
    w("                  expiry_tier, identity_mode, label_placement_note) VALUES")
    mode_b = [
        (9001, "Kirana Hair Serum 100 ml", "Hair Care", "Hair Serum", "100 ml", 78000, 520,
         "Tempel di belakang botol. Jangan tutup tanggal kadaluarsa."),
        (9002, "Kirana Face Mist 60 ml", "Face Care", "Face Mist", "60 ml", 52000, 300,
         "Tempel di badan botol, jangan di tutup."),
        (9003, "Kirana Body Lotion 200 ml", "Body Care", "Body Lotion", "200 ml", 64000, 700,
         "Tempel di belakang, jangan tutup logo."),
    ]
    w(",\n".join(
        "  ({i}, 2, {c}, {n}, {cat}, {ln}, {sz}, {p}, {cu}, 'stable', 'unit_label', {note})".format(
            i=i, c=esc(f"KRN-{i}"), n=esc(n), cat=esc(cat), ln=esc(ln),
            sz=esc(sz), p=p, cu=cu, note=esc(note),
        )
        for (i, n, cat, ln, sz, p, cu, note) in mode_b
    ) + ";")
    w("")

    w("-- Synthetic test barcodes, one per Mode A SKU (PRD M8.4.4).")
    w("INSERT INTO barcodes (barcode, sku_id, source, registered_by) VALUES")
    w(",\n".join(
        "  ('{bc}', {sid}, 'test_seed', 'seed@ninjavan.co')".format(bc=ean13(r["n"]), sid=r["n"])
        for r in rows
    ) + ";")
    w("")

    w("-- Training site layout: 7 racks x 5 levels x 3 medium positions (§2.3).")
    w("-- Rack G level 1 is an open shelf, mirroring hair care in the real model.")
    w("INSERT INTO racks (id, site_id, code, level_count, level_width_m, sort_order) VALUES")
    racks = ["A", "B", "C", "D", "E", "F", "G"]
    w(",\n".join(
        "  ({i}, 99, '{c}', 5, 1.00, {i})".format(i=i + 1, c=c) for i, c in enumerate(racks)
    ) + ";")
    w("")

    w("INSERT INTO levels (id, rack_id, level_no, is_open_shelf) VALUES")
    lv, level_rows, level_index = [], [], {}
    lid = 0
    for ri, rc in enumerate(racks, start=1):
        for ln in range(1, 6):
            lid += 1
            openshelf = 1 if (rc == "G" and ln == 1) else 0
            level_index[(rc, ln)] = lid
            lv.append(f"  ({lid}, {ri}, {ln}, {openshelf})")
            level_rows.append((lid, rc, ln, openshelf))
    w(",\n".join(lv) + ";")
    w("")

    w("INSERT INTO locations (id, level_id, site_id, position_no, code) VALUES")
    loc, loc_id = [], 0
    location_codes = []
    for (lid_, rc, ln, openshelf) in level_rows:
        positions = [0] if openshelf else [1, 2, 3]
        for p in positions:
            loc_id += 1
            code = f"TRN-{rc}-{ln}-{p:02d}"
            location_codes.append((loc_id, code, openshelf))
            loc.append(f"  ({loc_id}, {lid_}, 99, {p}, '{code}')")
    w(",\n".join(loc) + ";")
    w("")

    w("INSERT INTO baskets (id, location_id, site_id, basket_size) VALUES")
    w(",\n".join(
        "  ({i}, {i}, 99, '{s}')".format(i=i, s="OPEN" if openshelf else "M")
        for (i, _c, openshelf) in location_codes
    ) + ";")
    w("")

    n_baskets = len(location_codes)
    n_slots = min(n_baskets, len(rows))
    w(f"-- Slot the first {n_slots} Wardah SKUs into the first {n_slots} baskets.")
    w("INSERT INTO slot_assignments (site_id, sku_id, basket_id, created_by) VALUES")
    w(",\n".join(
        "  (99, {sku}, {basket}, 'seed@ninjavan.co')".format(sku=rows[i]["n"], basket=location_codes[i][0])
        for i in range(n_slots)
    ) + ";")
    w("")

    w("-- Opening stock: 55 units per SKU, the space model's base case")
    w("-- (max(6, 3/day x 14 DOI x 1.3)). training/reset restores exactly this.")
    w("INSERT INTO inventory_balances (site_id, sku_id, location_id, qty_on_hand) VALUES")
    w(",\n".join(
        "  (99, {sku}, {loc}, 55)".format(sku=rows[i]["n"], loc=location_codes[i][0])
        for i in range(n_slots)
    ) + ";")
    w("")

    w("-- A first user. Real emails are mapped in the portal once SSO is on;")
    w("-- with SSO off this row is what makes local dev usable.")
    w("INSERT INTO users (email, name, role, default_site_id, locale) VALUES")
    w("  ('dev@ninjavan.co', 'Dev (local)', 'admin', 99, 'id');")
    w("INSERT INTO user_sites (user_id, site_id) SELECT 1, id FROM sites;")
    w("")

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(rows)} Wardah SKUs, {n_baskets} baskets, {n_slots} slotted")


if __name__ == "__main__":
    main()
