#!/usr/bin/env python3
"""Generate backend/db/seed.sql: test data for the DEV environment only.

Substrait applies backend/db/seed.sql to non-production databases after the
Flyway migrations, and never to production. It seeds the Kahf and Labore pilot
(PRD v3.3) at KJ5 Kemanggisan (site 2) and MA5 Kalibata (site 4) so the Hiryu
bridge can be tested end to end:

  - brands Kahf and Labore, and their SKUs from the 25 Sep recheck lists
    (../Grab Kilat Fulfillment/*_sku_recheck.csv), bundles and doubtful rows
    left out, exactly as build_sku_master.py does; codes KHF-0001 / LBR-0001,
    with the Hiryu SKU code equal to the WMS code
  - the product barcode where the recheck found one, else a synthetic EAN-13
    in the 299 internal-use range so scanning can be tested
  - racks A to E (5 levels x 5 bins) at both hubs, one bin per SKU, 12 units
    each; a few SKUs also have units in a spare bin, to test "Cek dulu di
    tempat lain"
  - four TEST Hiryu stores (901 to 904) and one Hiryu item per SKU, plus one
    two-unit bundle and one item left unconnected, to test the paste checks

Nothing here is customer data. Re-runnable: every insert is INSERT IGNORE or
ON DUPLICATE KEY UPDATE.

    python tools/gen_dev_seed.py
"""
import csv
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT.parent / "Grab Kilat Fulfillment"
OUT = ROOT / "backend" / "db" / "seed.sql"
SAMPLE = ROOT / "docs" / "dev-test-orders.txt"

BRANDS = [(10, "KHF", "Kahf", "kahf"), (11, "LBR", "Labore", "labore")]
SITES = [(2, "KJR"), (4, "MA5")]
STORES = [(901, "Kahf - Kemanggisan (TEST)", 2, 10), (902, "Labore - Kemanggisan (TEST)", 2, 11),
          (903, "Kahf - Kalibata (TEST)", 4, 10), (904, "Labore - Kalibata (TEST)", 4, 11)]
RACKS, LEVELS, POSITIONS = "ABCDE", 5, 5


def esc(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("\\", "\\\\").replace("'", "''") + "'"


def num(v):
    d = re.sub(r"[^0-9]", "", str(v or "").split("(")[0])
    return d or "NULL"


def ean13(seed: int) -> str:
    body = "299" + str(seed).zfill(9)
    total = sum(int(c) * (3 if i % 2 else 1) for i, c in enumerate(body))
    return body + str((10 - total % 10) % 10)


def rows_for(stem):
    with open(SRC / f"{stem}_sku_recheck.csv", encoding="utf-8-sig", newline="") as fh:
        data = list(csv.DictReader(fh))
    out = []
    for r in data:
        status = (r.get("Status") or "kept").lower()
        bundle = (r.get("Bundle (Y/N)") or "").upper().startswith("Y")
        barcode = (r.get("Barcode EAN") or "").strip()
        kit = bundle and bool(barcode)
        if (bundle and not kit) or "discontinued" in status or "duplicate" in status:
            continue
        out.append(r)
    return out


def main():
    sql = ["-- GENERATED by tools/gen_dev_seed.py. Do not edit by hand.",
           "-- DEV ONLY: Substrait never applies this file to production.",
           "-- Kahf and Labore test data for the Hiryu bridge (PRD v3.3). No customer data.", ""]

    sql.append("INSERT INTO brands (id, code, name, identity_mode) VALUES")
    sql.append(",\n".join(f"  ({i}, '{c}', '{n}', 'sku_barcode')" for i, c, n, _ in BRANDS))
    sql.append("ON DUPLICATE KEY UPDATE name = VALUES(name);\n")

    sql.append("INSERT IGNORE INTO brand_sites (brand_id, site_id, active) VALUES")
    sql.append(",\n".join(f"  ({b}, {s}, 1)" for b, *_ in BRANDS for s in (2, 4, 99)) + ";\n")

    skus, barcodes, items, prices = [], [], [], []
    sku_rows = []           # (sku_id, brand_id, code, name, item_id, price)
    sku_id = 1000
    for brand_id, code, _name, stem in BRANDS:
        for n, r in enumerate(rows_for(stem), 1):
            sku_id += 1
            sku_code = f"{code}-{n:04d}"
            name = (r.get("Product name") or "").strip()
            size = (r.get("Unit size") or "").strip()
            price = num(r.get("Price (Rp)"))
            cube = num(r.get("Est. unit cube incl. carton (cm3)"))
            skus.append(f"  ({sku_id}, {brand_id}, {esc(sku_code)}, {esc(name)}, {esc(r.get('Category'))}, "
                        f"{esc(r.get('Product line'))}, {esc(size)}, {price}, {cube}, 'stable', 'sku_barcode', {esc(sku_code)})")
            bc = (r.get("Barcode EAN") or "").strip()
            bc = bc if re.fullmatch(r"\d{8,14}", bc) else ean13(sku_id)
            src = "manufacturer" if not bc.startswith("299") else "test"
            barcodes.append(f"  ({esc(bc)}, {sku_id}, '{src}', 'seed@ninjavan.co')")
            item_id = f"IDITE2026092{sku_id:08d}"
            item_name = f"{name} {size}".strip()   # Grab shows the size in the item name
            items.append(f"  ({esc(item_id)}, {brand_id}, {esc(item_name)}, {esc(bc)}, 'AVAILABLE', {sku_id}, 1, 'seed@ninjavan.co')")
            if price != "NULL":
                prices.append(f"  ({esc(item_id)}, {price}, '2026-09-28')")
            sku_rows.append((sku_id, brand_id, sku_code, item_name, item_id, price))

    sql.append("INSERT INTO skus (id, brand_id, brand_sku_code, name_display, category, product_line, unit_size, "
               "price_idr, unit_cube_cm3, expiry_tier, identity_mode, hiryu_sku_code) VALUES")
    sql.append(",\n".join(skus))
    sql.append("ON DUPLICATE KEY UPDATE name_display = VALUES(name_display), hiryu_sku_code = VALUES(hiryu_sku_code);\n")

    sql.append("INSERT IGNORE INTO barcodes (barcode, sku_id, source, registered_by) VALUES")
    sql.append(",\n".join(barcodes) + ";\n")

    # Racks, levels, bins, baskets per hub.
    rack_rows, level_rows, loc_rows, basket_rows = [], [], [], []
    loc_by_site = {}
    for si, (site_id, prefix) in enumerate(SITES):
        loc_by_site[site_id] = []
        for ri, rc in enumerate(RACKS):
            rack_id = 100 + si * 10 + ri
            rack_rows.append(f"  ({rack_id}, {site_id}, '{rc}', {LEVELS}, 1.00, {ri + 1})")
            for lv in range(1, LEVELS + 1):
                level_id = rack_id * 10 + lv
                level_rows.append(f"  ({level_id}, {rack_id}, {lv}, 0)")
                for pos in range(1, POSITIONS + 1):
                    loc_id = level_id * 10 + pos
                    code = f"{prefix}-{rc}-{lv}-{pos:02d}"
                    loc_rows.append(f"  ({loc_id}, {level_id}, {site_id}, {pos}, '{code}')")
                    basket_rows.append(f"  ({loc_id}, {loc_id}, {site_id}, 'M')")
                    loc_by_site[site_id].append(loc_id)

    sql.append("INSERT IGNORE INTO racks (id, site_id, code, level_count, level_width_m, sort_order) VALUES")
    sql.append(",\n".join(rack_rows) + ";\n")
    sql.append("INSERT IGNORE INTO levels (id, rack_id, level_no, is_open_shelf) VALUES")
    sql.append(",\n".join(level_rows) + ";\n")
    sql.append("INSERT IGNORE INTO locations (id, level_id, site_id, position_no, code) VALUES")
    sql.append(",\n".join(loc_rows) + ";\n")
    sql.append("INSERT IGNORE INTO baskets (id, location_id, site_id, basket_size) VALUES")
    sql.append(",\n".join(basket_rows) + ";\n")

    slots, balances = [], []
    for site_id, _ in SITES:
        locs = loc_by_site[site_id]
        for i, (sid, *_rest) in enumerate(sku_rows):
            loc = locs[i]
            slots.append(f"  ({site_id}, {sid}, {loc}, 'seed@ninjavan.co', 'primary', 24, 6)")
            # A few SKUs run low, to see the stock sheet and a missing item.
            qty = 1 if i % 17 == 5 else 12
            balances.append(f"  ({site_id}, {sid}, {loc}, {qty})")
        # Spare units in the last bins, with no slot: the "look elsewhere" test.
        for j in range(3):
            balances.append(f"  ({site_id}, {sku_rows[j][0]}, {locs[-1 - j]}, 4)")

    sql.append("INSERT IGNORE INTO slot_assignments (site_id, sku_id, basket_id, created_by, slot_role, "
               "full_threshold, restock_point) VALUES")
    sql.append(",\n".join(slots) + ";\n")
    sql.append("INSERT IGNORE INTO inventory_balances (site_id, sku_id, location_id, qty_on_hand) VALUES")
    sql.append(",\n".join(balances) + ";\n")

    sql.append("INSERT INTO hiryu_stores (hiryu_store_no, store_name, partner_store_id, site_id, brand_id, active, updated_by) VALUES")
    sql.append(",\n".join(f"  ({no}, {esc(nm)}, 'TEST-{no}', {s}, {b}, 1, 'seed@ninjavan.co')" for no, nm, s, b in STORES))
    sql.append("ON DUPLICATE KEY UPDATE store_name = VALUES(store_name);\n")

    # One bundle (2 units of the first Kahf SKU) and one unconnected item.
    first_kahf = sku_rows[0]
    items.append(f"  ('IDITE20260929000000001', 10, {esc('Paket isi 2: ' + first_kahf[3])}, NULL, 'AVAILABLE', {first_kahf[0]}, 2, 'seed@ninjavan.co')")
    items.append("  ('IDITE20260929000000002', 10, 'Kahf gift set (TEST, not connected)', NULL, 'AVAILABLE', NULL, 1, NULL)")
    sql.append("INSERT INTO hiryu_items (hiryu_item_id, brand_id, item_name, barcode, available_status, sku_id, "
               "units_per_sale, mapped_by) VALUES")
    sql.append(",\n".join(items))
    sql.append("ON DUPLICATE KEY UPDATE item_name = VALUES(item_name);\n")
    sql.append("INSERT IGNORE INTO hiryu_item_prices (hiryu_item_id, price_idr, effective_date) VALUES")
    sql.append(",\n".join(prices) + ";\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(sql) + "\n", encoding="utf-8")

    # Sample order pages to paste on dev: the same text Hiryu's order page gives.
    kahf = [r for r in sku_rows if r[1] == 10]
    lab = [r for r in sku_rows if r[1] == 11]

    def page(no, gid, store, items, acceptance="AUTO", status="RECEIVED", sched="—", note=None):
        units = sum(q for q, _ in items)
        lines = [f"Order {no}", status, "Accept", "Reject", "Details", "Grab order ID", gid, "Store",
                 f"View store #{store}", "Acceptance", acceptance, "Order time", "Sep 28, 2026, 02:27 PM",
                 "Scheduled time", sched, "Items",
                 f"{len(items)} line{'s' if len(items) != 1 else ''} · {units} unit{'s' if units != 1 else ''}"]
        for q, r in items:
            lines += [f"{q}×", r[3], r[4]]
            if note:
                lines.append(note)
                note = None
            lines += ["If out of stock: Remove item", f"IDR {r[5]}"]
        lines += ["Raw payload", "Show"]
        return "\n".join(lines)

    bundle = (1, (None, 10, None, "Paket isi 2: " + first_kahf[3], "IDITE20260929000000001", first_kahf[5]))
    unmapped = (1, (None, 10, None, "Kahf gift set (TEST, not connected)", "IDITE20260929000000002", "0"))
    samples = [
        ("1. A normal Kahf order at MA5 (with a customer note that must NOT reach the WMS)",
         page("GM-T001", "TEST-A1B2C3D4E5", 903, [(2, kahf[0]), (1, kahf[1])], note="Tolong dibungkus rapi ya kak")),
        ("2. A Labore order at MA5 whose second item has only 1 unit in its bin (test Barang tidak ada)",
         page("GM-T002", "TEST-F6G7H8J9K0", 904, [(1, lab[0]), (3, lab[5])])),
        ("3. A bundle: 1 x 'Paket isi 2' = 2 units of one SKU",
         page("GM-T003", "TEST-L1M2N3P4Q5", 903, [bundle])),
        ("4. Manual acceptance, not accepted yet (expect: Tekan Accept di Hiryu dulu)",
         page("GM-T004", "TEST-R6S7T8U9V0", 903, [(1, kahf[2])], acceptance="MANUAL")),
        ("5. An item not connected yet (expect: Barang belum dihubungkan, sent to Ops HQ)",
         page("GM-T005", "TEST-W1X2Y3Z4A5", 903, [unmapped])),
        ("6. The same order as 1, now cancelled in Hiryu (paste after 1)",
         page("GM-T001", "TEST-A1B2C3D4E5", 903, [(2, kahf[0]), (1, kahf[1])], status="CANCELLED")),
        ("7. A Kahf order at KJR (KJ5) pasted while the station is set to MA5 (expect: Toko ini milik hub lain)",
         page("GM-T007", "TEST-B6C7D8E9F0", 901, [(1, kahf[3])])),
    ]
    SAMPLE.write_text(
        "DEV TEST ORDERS: fake Hiryu order pages for wms-test--dev. Copy one block (between the lines)\n"
        "and paste it into Tempel pesanan Grab. Store numbers 901 to 904 are test stores from the dev seed.\n"
        "Set the station to MAC-MA5 first. The order time is fixed, so orders show as late: that is expected.\n\n" +
        "\n\n".join(f"{t}\n{'-' * 60}\n{p}\n{'-' * 60}" for t, p in samples) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(sku_rows)} SKUs "
          f"(Kahf {len(kahf)}, Labore {len(lab)}), {len(loc_rows)} bins; {SAMPLE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
